# Generated by Django 3.1.6 on 2021-02-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_teamsoccer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('P', 'Portero'), ('D', 'Defensa'), ('M', 'Mediocampista'), ('A', 'Atacante')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='teamsoccer',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
